Disable Portuguese translation
Breaks the build:

Error: Could not merge translations:
'NoneType' object has no attribute 'node'
Makefile:518: recipe for target 'pt/pt.stamp' failed
make[2]: *** [pt/pt.stamp] Error 1